# Generated by Django 5.1.5 on 2025-01-15 09:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagoery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groceries', models.FloatField(default=0)),
                ('leisure', models.FloatField(default=0)),
                ('electronics', models.FloatField(default=0)),
                ('utilities', models.FloatField(default=0)),
                ('clothing', models.FloatField(default=0)),
                ('health', models.FloatField(default=0)),
                ('others', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
